<?php

namespace Tests\Support;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Lightweight PostDraft model mirroring the fields used by the CreatePost component.
 */
class PostDraft extends Model
{
    use HasFactory;

    /**
     * Indicate that draft identifiers are string based.
     */
    public $incrementing = false;

    /**
     * Use string keys to match the uniqid() values generated by the component.
     */
    protected $keyType = 'string';

    /**
     * Table definition aligning with the in-memory schema created in Pest hooks.
     */
    protected $table = 'post_drafts';

    /**
     * Mass assignable attributes leveraged during updateOrCreate calls.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'id',
        'user_id',
        'content',
        'tags',
        'pet_id',
        'visibility',
    ];
}
